### ISSUE TITLE
Using more relaxed version numbers in the requirements file

### ISSUE THREAD

**Issue by rabin-io** [goldyfruit/ibmcloud-python-sdk#18]
Can the requirements be more relaxed? e.g., with botocore which force using boto version 1.13 while the latest release are on 1.26+

```
botocore==1.16.9
```

**Comment by goldyfruit** [comment]
Sorry I missed the issue...
Yes it can be relaxed, feel free to push a PR, I'll review it. :+1:

**Comment by rabin-io** [comment]
Hi @goldyfruit can you please take a look on the PR please?
