### ISSUE TITLE
Contributing?

### ISSUE THREAD

**Issue by mrodden** [goldyfruit/ibmcloud-python-sdk#3]
I just recently noticed your project here and there are quite a few APIs you have that are orthogonal to the work I have been doing at https://github.com/IBM/redstone

I didn't find a contributing section in your docs or the project here, and was wondering where you are collaborating, either within or without IBM.

**Comment by goldyfruit** [comment]
Hi @mrodden, this project is open source and not part of IBM.

We build this with @jamesregis to mostly backed our Ansible modules.

The contribution is very simple, just open a PR and we will review it for the merge.

Easy 😜

**Comment by goldyfruit** [comment]
Closing for now.
